006: CRUD events
DmytroTy/activity.ck.ua-backend pull request #10
Opened 2021-04-05 05:14 UTC by DmytroTy

2021-04-05 06:02 UTC, Roman-Kirnos requested changes

2021-04-05 06:02 UTC, Roma-Kyrnis commented on src/db/knex/migrations/20210209144414_createDB.js
> +    table.timestamp('end_time').notNullable();
Сейчас фронтенд и девопс работают уже с существующей базой. Предлагаю сделать новую миграцию для добавления новых полей и удаления старого

2021-04-05 06:02 UTC, Roma-Kyrnis commented on src/db/pg/events.js
> +            WHERE start_time > $1 AND start_time < $1 + INTERVAL '2 week' AND end_time > now()
`2 week` нужно вынести в конфиг

2021-04-05 06:02 UTC, Roma-Kyrnis commented on src/db/pg/events.js
> +        }
Предлагаю вынести в функцию потому, что два раза повторяется и меньше кода в функции `getCurrentEvents` и `getEvents` будет

2021-04-05 06:02 UTC, Roma-Kyrnis commented on src/db/pg/events.js
> +            WHERE end_time > now() AND end_time < TIMESTAMP 'tomorrow' AND start_time < now()
`tomorrow` в конфиг лучше вынести

2021-04-05 10:40 UTC, Roman-Kirnos commented
На странице мест у нас показываются события, которые будут проходить на этом месте. Можешь сделать запрос на получение событий по `place_id`

2021-04-05 11:09 UTC, DmytroTy commented on src/db/pg/events.js
> +            WHERE end_time > now() AND end_time < TIMESTAMP 'tomorrow' AND start_time < now()
А отут не погоджусь, today, tomorrow це не змінні параметри, а фіксовані, тому нема чого в конфіг виносити й тільки срач там розводити.

2021-04-05 12:39 UTC, DmytroTy commented
Все готово.

2021-04-05 20:39 UTC, Roman-Kirnos commented on src/db/pg/events.js
> +            WHERE end_time > now() AND end_time < TIMESTAMP 'tomorrow' AND start_time < now()
> А отут не погоджусь, today, tomorrow це не змінні параметри, а фіксовані, тому нема чого в конфіг виносити й тільки срач там розводити.

Да, они не изменные. Но их тоже нужно выносить в конфиг, что бы сразу видеть, что установлено. В конфиге находятся все константы, то есть не изменные данных

2021-04-05 20:39 UTC, Roman-Kirnos commented on src/db/pg/events.js
> +            WHERE end_time > now() AND end_time < TIMESTAMP 'tomorrow' AND start_time < now()
Можешь у менторов за это спросить

2021-04-05 21:39 UTC, Roman-Kirnos requested changes

2021-04-05 21:39 UTC, Roman-Kirnos commented on src/db/pg/events.js
> +    getPlaceEvents: async (placeId, limit = PLACE_PAGE_EVENTS_COUNT, page = 1) => {
Страницу тоже в конфиг. Все константы в конфиге должны быть

2021-04-05 21:39 UTC, Roman-Kirnos commented on src/config/index.js
> +    PLACE_PAGE_EVENTS_COUNT: 5,
`QUANTITY_EVENTS_ON_PLACE`?

2021-04-05 21:39 UTC, Roman-Kirnos commented on src/db/pg/events.js
> +    getPlaceEvents: async (placeId, limit = PLACE_PAGE_EVENTS_COUNT, page = 1) => {
Это менторы говорили

2021-04-05 21:40 UTC, Roman-Kirnos commented on src/db/pg/events.js
> +    getPlaceEvents: async (placeId, limit = PLACE_PAGE_EVENTS_COUNT, page = 1) => {
Потому, что удобно видеть все сразу в одном месте

2021-04-06 04:14 UTC, DmytroTy commented on src/db/pg/events.js
> +            WHERE end_time > now() AND end_time < TIMESTAMP 'tomorrow' AND start_time < now()
> Да, они не изменные. Но их тоже нужно выносить в конфиг, что бы сразу видеть, что установлено. В конфиге находятся все константы, то есть не изменные данных

Повторю ще раз: поточний день і поточний час як варіант вибору тільки поточних подій не є конфігурацією, а само собою розуміється, що сьогодні й зараз це сьогодні і ніяк по іншому бути не може в принципі!

2021-04-06 04:16 UTC, DmytroTy commented on src/db/pg/events.js
> +            WHERE end_time > now() AND end_time < TIMESTAMP 'tomorrow' AND start_time < now()
> Можешь у менторов за это спросить

Там де встановлюється період для наступних подій подій в конфіг виніс!
А поточний день не є параметром, який з чимось іншим можна сплутати!
Я там так і порівнюю, що сьогодні, це значить раніше ніж наступить завтра!

2021-04-06 04:20 UTC, DmytroTy commented on src/db/pg/events.js
> +    getPlaceEvents: async (placeId, limit = PLACE_PAGE_EVENTS_COUNT, page = 1) => {
> Это менторы говорили

Не пам'ятаю.

2021-04-06 04:23 UTC, DmytroTy commented on src/config/index.js
> +    PLACE_PAGE_EVENTS_COUNT: 5,
А це не одне й те ж саме?
І якщо вже правильно твою фразу тоді слід писати так: QUANTITY_OF_EVENTS_ON_PLACE_PAGE
Я записав це більш коротко й лаконічно.

2021-04-06 07:23 UTC, Roman-Kirnos commented on src/config/index.js
> +    PLACE_PAGE_EVENTS_COUNT: 5,
Нет, это не однаково. Так название читабилней и быстрей понятно к чему относится данное значение

2021-04-07 07:32 UTC, merged