004 events
DmytroTy/activity.ck.ua-backend pull request #15
Opened 2021-04-07 07:33 UTC by Roman-Kirnos

2021-04-07 15:48 UTC, DmytroTy requested changes
Правки необхідно внести до завтрашнього обіду, інакше нам нічого буде показати увечері на звіті!

2021-04-07 15:48 UTC, DmytroTy commented on src/db/pg/events.js
> +    getUserEvents: async (userId, limit, page = 1) => {
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!
(тим паче засунути це в написаний мною код...)

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/api_v1/auth.js
> +const router = Router();
Ще ж зовсім недавно тобі подобалось правильно писати код. А зараз що змінилось?

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/api_v1/index.js
> +const router = Router();
Тут аналогічно.

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +const router = Router();
Тут також аналогічно.

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +const router = Router();
Тут також аналогічно.

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/index.js
> +const router = Router();
Тут також аналогічно.

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +  ctx.assert(event, 400, `Cannot find event with id ${id}`);
404

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +  ctx.body = { ...events };
Що за дурня?
Я знаю як ти любиш деструктуризацію, але розкласти масив на окремі елементи й запхнути їх в об'єкт... ?

Не можна було нормально зробити: 
ctx.body = events;

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +  ctx.body = { ...events };
Тут аналогічно.

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +  const event = await updateEvent({ id, ...ctx.request.body.event });
Зайве перезбирання об'єкта як і дубляж id тут не потрібно!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +  ctx.assert(event, 400, `No event with id ${id}`);
404

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/api_v1/events.js
> +);
Ми ж домовились на загальному обговоренні вже давно, що переглядати вміст сайту можуть всі! А не тільки зареєстровані на сайті!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/router/api_v1/events.js
> +router.delete('/:id', { validate: validator.remove }, access(), events.remove);
Ми ж домовились на загальному обговоренні вже давно і навіть у вівторок це проговорювали знову, що редагувати свій власний контент можуть всі зареєстровані користувачі, а не тільки модератор!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  if (childFriendly !== undefined) filters.childFriendly = childFriendly;
Цей код дублюється, ти ж вже в цьому пулл реквесті зробив для цього окрему функцію!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  const events = await getEventsDB({ ...filters, place_id: id }, limit, page);
Мало того що всі ці деструктуризації й перезбирання не потрібні, так ще не працює, бо функція розрахована на отримання параметрів (startTime, limit, page, filters)

І взагалі це зовсім не та функція підключена! Ще дивніше, що в цьому ж файлі вище підключена потрібна функція. І взагалі як можна було додуматись на одну й ту ж саму дію підключати різні функції?

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  page = parseInt(page, 10) || EVENTS.PAGE;
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  page = parseInt(page, 10) || EVENTS.PAGE;
![Зняток екрану як 2021-04-07 16-43-30](https://user-images.githubusercontent.com/44680326/113876714-aaccde00-97c0-11eb-9c0c-9a7e7ff96508.png)
І тут аналогічно!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +    ctx.body = { place, photos, events };
І до чого відносяться ці фотографії: до місць чи подій?
До змін було зрозуміло до чого вони відносяться, а тепер ні!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
>  } = require('../../../config');
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  getEvents: getEventsDB,
Це взагалі не для місць!
Рядком вище ж правильний варіант вже є!

2021-04-07 15:48 UTC, DmytroTy commented on src/config/index.js
> +  },
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/config/index.js
> +      },
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/config/index.js
> +      START_TIME: new Date().setHours(0, 0, 0, 0),
Ментори ж тобі буквально вчора відповіли, що такого в конфіг не потрібно виносити!

![Зняток екрану як 2021-04-07 16-54-27](https://user-images.githubusercontent.com/44680326/113878167-09df2280-97c2-11eb-8146-31ddc035a1bd.png)

2021-04-07 15:48 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +      organizer: Joi.string().min(3),
Це поле є обов'язковим!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +    start_time: Joi.date().default(EVENTS.DEFAULT.START_TIME),
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +      .default(EVENTS.DEFAULT.PAGE),
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +      .default(EVENTS.DEFAULT.LIMIT),
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +      .default(EVENTS.DEFAULT.PAGE),
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 15:48 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +      .default(EVENTS.DEFAULT.LIMIT),
Ми ж вчора на загальному обговоренні остаточно затвердили такого не робити!

2021-04-07 20:36 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +    ctx.body = { place, photos, events };
Просто повернути назад без зайвої деструктуризації!

2021-04-08 10:28 UTC, DmytroTy requested changes

2021-04-08 10:28 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +    ctx.body = { place: { ...place, photos } };
Тут в деструктуризації й перезбиранні об'єкта немає ніякої потреби!
Краще поверни простий варіант як було.

2021-04-08 10:28 UTC, DmytroTy commented on src/server/schema/api_v1/events.js
> +      id: Joi.number().min(1).required(),
Й не забудь і тут як ментори сказали змінити.

2021-04-08 15:27 UTC, DmytroTy requested changes
Ще кілька помилок в доданому коді.

2021-04-08 15:27 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +    const isValid = await isUserEvent(userId, ctx.request.body.event.id);
Тепер в тебе ж цієї id в body більше немає.
Візьми ту що вище витягнув з params

2021-04-08 15:27 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +    event = await updateEvent({ ...ctx.request.body.event, id });
Тут мабуть потрібно додати поле moderated: true

2021-04-08 15:27 UTC, DmytroTy commented on src/server/controller/api_v1/events.js
> +    const isValid = await isUserEvent(userId, ctx.request.body.event.id);
Тут взагалі в цьому запиті ніякого body немає!
Візьми id витягнуту вище з params

2021-04-08 15:28 UTC, DmytroTy commented
Також потрібно зробити права доступу й на редагування місць, а то зараз абсолютно всім доступно:

![Зняток екрану як 2021-04-08 18-14-01](https://user-images.githubusercontent.com/44680326/114054059-2fd6f680-9898-11eb-82bd-afb6c8960e50.png)

2021-04-08 16:40 UTC, Roman-Kirnos commented on src/server/controller/api_v1/events.js
> +    event = await updateEvent({ ...ctx.request.body.event, id });
Админ сам будет добавлять это поле в body. Я сделал для него валидацию

2021-04-08 18:44 UTC, DmytroTy requested changes

2021-04-08 18:44 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +router.delete('/:id', { validate: validator.remove }, access(), places.remove);
Потрібно однак зробити нормальний доступ для всіх зареєстрованих користувачів як і в подіях з перевіркою права на редагування.

2021-04-08 18:45 UTC, merged