007: CR&D users activities was added
DmytroTy/activity.ck.ua-backend pull request #23
Opened 2021-04-09 14:52 UTC by DmytroTy

2021-04-09 16:46 UTC, Roman-Kirnos requested changes

2021-04-09 16:46 UTC, Roman-Kirnos commented on src/db/pg/activities.js
> +        throw checkError(err);
`checkError` можешь доделать проверку на внешний ключ. Сейчас функция не словит ни одной ошибки. И в следующих 2-х функциях тоже

2021-04-12 14:34 UTC, DmytroTy commented on src/db/pg/activities.js
> +        throw checkError(err);
Доповнив правила обробки помилок.

2021-04-13 04:32 UTC, Roman-Kirnos requested changes

2021-04-13 04:32 UTC, Roman-Kirnos commented on src/db/checkError.js
> +    return new DatabaseError('ERROR: A place with this ID alredy favorite!');
В слове `already` буквы не хватает, в visited, в scheduled тоже. И `favorited` будет правильно потому, что `уже добавлено в избранное`

2021-04-13 07:24 UTC, DmytroTy commented on src/db/checkError.js
> +    return new DatabaseError('ERROR: A place with this ID alredy favorite!');
> В слове `already` буквы не хватает, в visited, в scheduled тоже.

Виправив.

2021-04-13 07:25 UTC, DmytroTy commented on src/db/checkError.js
> +    return new DatabaseError('ERROR: A place with this ID alredy favorite!');
> И `favorited` будет правильно потому, что `уже добавлено в избранное`

Це прикметник, а не дієслово, тому не відмінюється!

2021-04-13 07:41 UTC, DmytroTy commented on src/db/checkError.js
> +    return new DatabaseError('ERROR: A place with this ID alredy favorite!');
> И `favorited` будет правильно потому, что `уже добавлено в избранное`

Це прикметник, а не дієслово, тому не відмінюється!

В себе в коді ти зробив аналогічну помилку, подивись.

2021-04-13 08:36 UTC, merged