003.1 server users page without authorization
DmytroTy/activity.ck.ua-backend pull request #24
Opened 2021-04-09 17:41 UTC by Roman-Kirnos

2021-04-12 17:40 UTC, DmytroTy requested changes

2021-04-12 17:40 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = { places };
Всередині об'єкта вже є вкладений масив "places", тому краще не вкладай в ще один з такою ж назвою об'єкт.

2021-04-12 17:40 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = { events };
Всередині об'єкта вже є вкладений масив "events", тому краще не вкладай в ще один з такою ж назвою об'єкт.

2021-04-12 17:40 UTC, DmytroTy commented on src/server/router/api_v1/events.js
> +);
Можливо логічніше це відправляти все ж на користувача, так як ця інформація користувача куди більше стосується ніж самої події?

2021-04-12 17:40 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +);
Аналогічно, все це більше стосується користувача (який відвідує місце) ніж самого місця.

2021-04-12 17:40 UTC, DmytroTy commented on src/server/router/api_v1/users.js
> +myself.prefix(USERS_MYSELF);
Судячи з конфігу тут частина шляху '/users' пропущена?

2021-04-12 17:45 UTC, DmytroTy commented
Й потрібно трохи підправити щоб сьогодні доданий функціонал працював.

2021-04-13 07:48 UTC, DmytroTy commented on src/server/router/api_v1/users.js
> +myself.prefix(USERS_MYSELF);
А цей:
router.prefix(USERS);
в тебе ж ніде навіть не використовується!

2021-04-13 08:37 UTC, Roman-Kirnos commented on src/server/controller/api_v1/users.js
> +  ctx.body = { places };
Это уже исправлено

2021-04-13 08:37 UTC, Roman-Kirnos commented on src/server/controller/api_v1/users.js
> +  ctx.body = { events };
Это исправлено

2021-04-13 08:39 UTC, Roman-Kirnos commented on src/server/router/api_v1/users.js
> +myself.prefix(USERS_MYSELF);
Я думаю лучше разделить по разным путям

2021-04-13 08:40 UTC, DmytroTy requested changes
Знову хтозна що в нових змінах.

Також просив же: додай до функцій отримання місць і подій ще один додатковий параметр, щоб працював новий вчора доданий функціонал.

2021-04-13 08:40 UTC, DmytroTy commented on src/config/index.js
> +      USERS: { MAIN: '/users', MYSELF: '/myself' },
'/users' пропущено в роутах!
Крім того '/users' окремо ніде й не використовував.

2021-04-13 08:40 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = response;
Що за єрунда знову.
Для чого?

2021-04-13 08:40 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = response;
Що за єрунда знову.
Для чого?

Й граматична помилка в слові favorite тут є.

2021-04-13 08:40 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = response;
Що за єрунда знову.
Для чого?

2021-04-13 08:40 UTC, DmytroTy commented on src/server/router/api_v1/users.js
> +router.prefix(USERS.MAIN);
Це ж ніде не використовував.
Тоді для чого це?

2021-04-13 08:40 UTC, DmytroTy commented on src/server/router/api_v1/users.js
> +myself.prefix(USERS.MYSELF);
Тут однак пропущений початок шляху - '/users'!

2021-04-13 08:43 UTC, DmytroTy commented on src/server/router/api_v1/users.js
> +myself.prefix(USERS_MYSELF);
Що розділити, коли ти його зовсім ніде не використовуєш?

2021-04-13 09:39 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = response;
До змін же було нормально!

2021-04-13 09:39 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = response;
До змін же було нормально!

2021-04-13 09:39 UTC, DmytroTy commented on src/server/controller/api_v1/users.js
> +  ctx.body = response;
До змін же було нормально!

2021-04-13 11:28 UTC, Roman-Kirnos commented
Не вижу ошибки в том, что два роутера `/users` и `/myself` как отдельные значения в конфиге. Это я так пишу код, мое мнение

2021-04-13 12:24 UTC, DmytroTy commented
> Не вижу ошибки в том, что два роутера `/users` и `/myself` как отдельные значения в конфиге. Это я так пишу код, мое мнение

Так /users ти ніде не використовуєш, крім того про цю частину шляху взагалі повністю забув!
Я вже не знаю як це ще можна пояснити?

2021-04-13 13:40 UTC, Roman-Kirnos commented
У тебя работает путь GET `/users/myself/favorite_places/`?

2021-04-14 09:34 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      return role;
Єдине питання: чому функція "isAccess" стала повертати "role" замість "true"

2021-04-14 09:35 UTC, DmytroTy approved these changes

2021-04-14 09:39 UTC, merged

2021-04-14 10:27 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      return role;
Ще тут занадто складна логіка (на що не було потреби), але це вже ладно.