002 server Places
DmytroTy/activity.ck.ua-backend pull request #3
Opened 2021-03-13 15:12 UTC by Roman-Kirnos

2021-03-13 16:29 UTC, DmytroTy requested changes

2021-03-13 16:29 UTC, DmytroTy commented on package.json
> +  "main": "main.js",
Шлях точно потрібно видалити?

2021-03-13 16:29 UTC, DmytroTy commented on docker-compose.yaml
> +    restart: always
Перехід на новий рядок забув?

2021-03-13 16:29 UTC, DmytroTy commented on .env.example
> -NODE_ENV=development
І для чого видалив, як буде працювати там де використовується?

2021-03-13 16:29 UTC, DmytroTy commented on src/config/index.js
> +    NODE_ENV: process.env.NODE_ENV,
Як це буде працювати після видалення даної змінної?

2021-03-13 16:29 UTC, DmytroTy commented on src/db/index.js
> +      if (k === 'knex') continue;
Як я пропонував зробити нормально файл, так ні, а сюди всунути таку фігню, так можна?

2021-03-13 16:29 UTC, DmytroTy commented on src/db/pg/places.js
> -            ORDER BY popularity_rating DESC
Я ж тобі сказав, що це сортування.
Давай перш ніж щось видаляти з мого коду про це як мінімум домовлятись!

2021-03-13 17:16 UTC, Roman-Kirnos commented on docker-compose.yaml
> +    restart: always
Где? Зачем?

2021-03-13 17:17 UTC, Roman-Kirnos commented on .env.example
> -NODE_ENV=development
Это для production не нужно

2021-03-13 17:19 UTC, Roman-Kirnos commented on src/db/pg/places.js
> -            ORDER BY popularity_rating DESC
Я удалил, что бы работало. Но забыл добавить в коммите

2021-03-14 06:56 UTC, Roman-Kirnos commented
Можешь еще код посмотреть. Возможно где-то можно лучше написать

2021-03-14 08:21 UTC, DmytroTy commented on docker-compose.yaml
> +    restart: always
В кінці кожного файлу прийнято додавати, щоб не було проблем, і тут є попередження про відсутність переходу на новий рядок.

2021-03-14 08:23 UTC, DmytroTy commented on .env.example
> -NODE_ENV=development
По-перше ти його видалив для development!
По-друге це стандартна змінна, яка в кінці розробки змінюється на production, але залишається!

2021-03-14 08:26 UTC, DmytroTy commented on src/db/pg/places.js
> -            ORDER BY popularity_rating DESC
Це не в тому рядку, я відразу помилився не туди глянувши.

2021-03-14 08:40 UTC, DmytroTy commented on src/config/index.js
> +    NODE_ENV: process.env.NODE_ENV || 'production',
Тобі не здається, що тут використовується змінна оточення NODE_ENV яку ти видалив і це перетворилось на повну фігню через те.

2021-03-14 10:37 UTC, DmytroTy commented
Пропоную таке "швидке" вирішення проблеми з конфігом knex.
Доповнив .dockerignore, бо половини не вистачало.

2021-03-16 21:13 UTC, Roman-Kirnos commented on src/config/index.js
> +    NODE_ENV: process.env.NODE_ENV || 'production',
Все отлично

2021-03-16 21:15 UTC, Roman-Kirnos commented
- [ ] Изменить тип поля `refresh_token` в таблице пользователей на `string`

Сейчас не работает авторизация потому, что тип поля `UUID`.

2021-03-17 12:43 UTC, Roman-Kirnos commented on docker-compose.yaml
> +    restart: always
Добавил

2021-03-17 12:44 UTC, Roman-Kirnos commented on .env.example
> -NODE_ENV=development
Development мы у себя в .env локально указываем. А с github его будет скачивать front-end, а они используют production.

2021-03-17 12:45 UTC, Roman-Kirnos commented on src/config/index.js
> +    NODE_ENV: process.env.NODE_ENV,
Я установил значение default

2021-03-18 11:22 UTC, DmytroTy commented on src/config/index.js
> +    NODE_ENV: process.env.NODE_ENV || 'production',
Було б, якби змінну не видалив.
А так виходить що фактично зробив: NODE_ENV: Undefined || 'production',

2021-03-18 20:42 UTC, DmytroTy reviewed
З авторизацією поки не розібрався, потім ще й по ній відпишу.

2021-03-18 20:42 UTC, DmytroTy commented on src/main.js
> +    await close();
Тут не close а end метод потрібно викликати, щоб закрити всі підключені модулі, а не один.

2021-03-18 20:42 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +}
Додаткові функції для однієї дії не потрібні. Можеш написати прямо там де необхідна цю дію.

2021-03-18 20:42 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  if (!id || Number.isNaN(id)) ctx.throw(400, 'Incorrect id');
|| Number.isNaN(id) зовсім не потрібно.

2021-03-18 20:42 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  const id = parseInt(ctx.request.params.id, 10);
Здається більш ефективно використовувати Number() ніж parseInt(), який через це вже не популярний.

2021-03-18 20:42 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  await updatePlace({ id, place: ctx.request.body.place });
Оце так не піде, нічого додаткового й зайвої вкладеності не потрібно робити.

2021-03-18 20:42 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +}
Для чого додаткова функція? Вона ж нічого не робить.

2021-03-18 20:42 UTC, DmytroTy commented on src/utils/authorizationTokens.js
> +  return await jwt.verify(token, secretKey);
Для чого додаткові функції, які нічого не роблять?

2021-03-18 20:42 UTC, DmytroTy commented on src/utils/authorizationTokens.js
> +  verifyToken,
І назовні вони мабуть ніде не використовуються, бо не потрібні.

2021-03-18 20:42 UTC, DmytroTy commented on src/utils/logger.js
> +    timestamp: () => `,"time":"${new Date(Date.now()).toUTCString()}"`,
Date.now() тут не потрібно.

2021-03-19 08:38 UTC, Roman-Kirnos commented on src/server/middleware/errorHandler.js
> +}
Что бы вызывать и будет single-tone патерн использован

2021-03-19 08:45 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +}
module.exports = handler; - буде абсолютно те ж саме, а додаткова функція зайва.

2021-03-25 08:18 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +}
Була б якась потреба туди передавати додаткові параметри, то можна було б, а в такому вигляді абсолютно зайве.

2021-03-25 08:37 UTC, DmytroTy requested changes
З новими комітами прийшли нові проблеми.
Авторизація явно не робоча, дарма ти її додав в це й же пулл реквест.

2021-03-25 08:37 UTC, DmytroTy commented on src/utils/authorizationTokens.js
> +  return await jwt.sign(payload, ACCESS_TOKEN_SECRET, ACCESS_TOKEN_LIFE);
Мабуть потрібно все ж { expiresIn: ACCESS_TOKEN_LIFE }
А то не буде працювати, потрібно уважніше змінювати.

2021-03-25 08:37 UTC, DmytroTy commented on src/utils/authorizationTokens.js
> +  return await jwt.sign(payload, REFRESH_TOKEN_SECRET, REFRESH_TOKEN_LIFE);
Мабуть потрібно все ж { expiresIn: REFRESH_TOKEN_LIFE }
А то не буде працювати, потрібно уважніше змінювати.

2021-03-25 08:37 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      ctx.assert(data.role === role || data.role === MODERATOR, 401, 'Access denied for user');
Умова точно не правильна, так не працюватиме!

2021-03-25 09:02 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  if (!id || Number.isNaN(id)) ctx.throw(400, 'Incorrect id');
Мабуть умову не слід було видаляти повністю, раз цю id використовуєш.
Я вказав тільки на зайву зовсім не функціональну її частину.

2021-03-25 11:54 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      ctx.assert(data.role === role || data.role === MODERATOR, 401, 'Access denied for user');
Ты проверял? Покажи

2021-03-25 14:42 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      ctx.assert(data.role === role || data.role === MODERATOR, 401, 'Access denied for user');
Все работает. Я проверил

2021-03-27 09:38 UTC, DmytroTy commented on src/server/schema/api_v1/places.js
> +      phones: Joi.array().items(Joi.string().pattern(/^\+380\d{9}$/)),
Мабуть все ж потрібно перевіряти обов'язковість наявності самого масиву, але можна й пустого.

2021-03-27 12:01 UTC, DmytroTy requested changes
Закінчив останнє рев'ю.
Там ще багато змін з логером було. З послідовністю передачі параметрів нічого не наплутав?

2021-03-27 12:01 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +async function getAll(ctx) {
Назва не правильна, ти ж не всі береш!

2021-03-27 12:01 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +router.get('/', { validate: validator.getAll }, places.getAll);
Назва не правильна, ти ж не всі береш!

2021-03-27 12:01 UTC, DmytroTy commented on src/server/schema/api_v1/auth.js
> +      .pattern(/^[a-zA-Z]+$/)
Занадто жорстке обмеження символів, будуть проблеми!

2021-03-27 12:01 UTC, DmytroTy commented on src/server/schema/api_v1/places.js
> +    photos: Joi.array().items(
Мабуть слід перевіряти щоб масив був і причому не пустий.

2021-03-27 12:01 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  }
Таке нікуди не годиться: дуже ресурсоємно й довго кожен об'єкт і масив перезбирати заново.
Тому єдиний аргумент "швидше" для безпідставного ускладнення коду зовсім себе не виправдав - не буде це швидше!

2021-03-27 12:01 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Має бути &&
різницю вловлюєш?

2021-03-27 12:04 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      ctx.assert(data.role === role || data.role === MODERATOR, 401, 'Access denied for user');
Точно?
Мабуть ти хотів перевірити:
data.role === role && data.role === MODERATOR
Різницю вловлюєш?

2021-03-27 16:12 UTC, Roman-Kirnos commented on src/server/schema/api_v1/places.js
> +      phones: Joi.array().items(Joi.string().pattern(/^\+380\d{9}$/)),
Добавил стандартное значение `[ ]`

2021-03-27 16:16 UTC, Roman-Kirnos commented on src/server/router/api_v1/places.js
> +router.get('/', { validate: validator.getAll }, places.getAll);
Можешь одну строчку кода в дальнейшем выделять, там где сама проблема

2021-03-27 16:23 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Здесь правильно написано. Доступ разрешен пользователю с указанной `role` в параметре функции или если этот пользователь модератор

2021-03-27 16:24 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  }
Другой вариант, только делать два запроса в базу. База работает с жестким диском, а программа выполняется в процессоре. Я думаю процессор быстрей будет

2021-03-27 16:27 UTC, Roman-Kirnos commented on src/server/schema/api_v1/auth.js
> +      .pattern(/^[a-zA-Z]+$/)
Исправил. И правда, было бы ограничение на русские и украинские символы

2021-03-27 16:28 UTC, Roman-Kirnos commented on src/server/controller/api_v1/places.js
> +async function getAll(ctx) {
Изменил название на `getApproved`

2021-03-27 16:28 UTC, Roman-Kirnos commented on src/server/schema/api_v1/places.js
> +    photos: Joi.array().items(
А обязательно должна быть фотография у места?

2021-03-27 18:00 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +async function getAll(ctx) {
Ладно, хоч не всі (бо враховуючи фільтрацію там ніяк не назвеш "всі").

2021-03-27 18:01 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +router.get('/', { validate: validator.getAll }, places.getAll);
Якщо ти не помітив я на одну й писав, а Гітхаб показує ще 3 попередні щоб було більш зрозуміліше про що це йдеться.

2021-03-27 18:08 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  }
Не в процесорі, а в оперативній пам'яті, й така глибока переробка великої кількості даних буде довго також робитись.
Головна проблема в тому що в БД така робота оптимізована, а тут якраз нераціональна довготривала робота в якій немає потреби зовсім.
Крім того швидкість SSD з якого БД навіть зчитуватиметься всього в 5 разів менша ніж оперативної пам'яті.
Та коли виконувати два запити одночасно, то й результати повернуться практично одночасно й не доведеться взагалі нічого чекати. Твоя переробка порядком довше робитиметься! Не роблять роботу замість БД прямо в коді через це.

2021-03-27 20:29 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Так тут доступ тільки модератору чи всім користувачам перевіряється?

2021-03-27 20:37 UTC, DmytroTy requested changes
В авторизації також виявляється є проблеми, добре що вона поки не використовувалась.

2021-03-27 20:37 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +function access(role) {
Цікава ситуація - а звідки ти візьмеш role щоб сюди передати, якщо його ще немає? (бо тільки в цій функції буде запущено його витягання.)

2021-03-27 20:37 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +function checkAccessToken(role) {
І тут також role не буде щоб передати.

2021-03-27 20:54 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Доступ разрешается из указанных ролей, те что находятся в переменной `role`, массивом.
А если такая роль не действительна для данного запроса, тогда проверяется, что пользователь модератор, если да то пропускает

2021-03-27 20:55 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  }
Завтра у менторов спрошу

2021-03-27 21:06 UTC, Roman-Kirnos commented
Не хочу наградить или оскорбить. Но мне интересно ты проверял как оно работает?

Так бы меньше вопросов было, почему там ИЛИ, а не `И`.

2021-03-27 21:27 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +function access(role) {
С начало `role` была просто строкой, но потом я переделал на массив и забыл проверить. Поэтому сейчас я установил значение по умолчанию и переделал функцию `.find` по массиву ролей

2021-03-28 03:43 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +function access(role) {
Так ти забув цей масив "roles" чи рядок туди взагалі передати. Як я маю догадатись що ти хотів і як помилився?

2021-03-28 03:45 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Тоді питання, а чому роль модератора має бути не дійсною для якихось запитів?
Може просто не працювало й дописував зайве...

2021-03-28 03:47 UTC, DmytroTy commented
> Не хочу нагрубить или оскорбить. Но мне интересно ты проверял как оно работает?
> 
> Так бы меньше вопросов было, почему там `ИЛИ`, а не `И`.

А собі таке питання не хочеш постави, а то я по 5 раз розповідаю одне й те ж саме аналогічно!

2021-03-28 03:51 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +router.post('/', { validate: validator.create }, access(), places.create);
Тоді виходить саме тут ти просто забув цей масив "roles" чи рядок передати (я ж не можу точно передбачити що саме ти думав зробити).

2021-03-28 07:09 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Возможно ты не правильно понял.
Модератор имеет доступ ко всем запросам

2021-03-28 07:20 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +function checkAccessToken(roles = []) {
Если ничего не передается, тогда `roles` массив. И доступ разрешен, только модератору

2021-03-28 07:28 UTC, Roman-Kirnos commented on src/server/middleware/errorHandler.js
> +}
Мне так нравится писать `middleware`

2021-03-29 06:13 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  }
Переделал на два запроса из базы

2021-03-29 15:17 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Я запитую: з якого дива в модератора має бути назначений менший доступ до якихось запитів ніж в інших користувачів?

2021-03-29 20:44 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
А почему меньший доступ. Ты путаешь. У модератора есть ко всем запросам доступ и все. Какая разница, что это установлено 2 параметром после ИЛИ

2021-03-30 03:57 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +  if (incomingError.name === DATABASE) ctx.status = 400;
Конкретніше, не просто абстрактна 400, а 409.

2021-03-30 04:33 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
> Доступ разрешается из указанных ролей, те что находятся в переменной `role`, массивом.
> А если такая роль не действительна для данного запроса, тогда проверяется, что пользователь модератор, если да то пропускает

Перефразую так: а чому для модератора з самого початку має бути закритий доступ до якихось запитів, який ти потім однак відкриваєш тільки по-іншому?

2021-03-30 04:37 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +router.post('/', { validate: validator.create }, access(), places.create);
Якщо робиш такий важливий масив-список ролей для яких відкритий доступ до запитів, то як тут можна забути його передати? Тобто доступ обмежив, а ролі яким доступно зовсім не передав!

2021-03-30 04:38 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +function checkAccessToken(roles = []) {
Через те що там вище не передаєш сюди нічого й не передається. 
Питання в тому чому не передаєш?

2021-03-30 04:52 UTC, DmytroTy commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
> А почему меньший доступ. Ты путаешь. У модератора есть ко всем запросам доступ и все. Какая разница, что это установлено 2 параметром после ИЛИ

Спочатку ти закрив доступ до запитів усім, включаючи й модератора (бо не передав жодної дозволеної ролі)!
А потім перевіряючи кому дозволений доступ вирішив модератору все ж дозволити.
Може з самого початку слід в дозволені ролі внести як мінімум модератора?

2021-03-30 07:48 UTC, Roman-Kirnos commented on src/server/middleware/checkTokens.js
> +      // role.find(data.role) || data.role === MODERATOR,
Можно не передавать роль модератора. Если это модератор то он будет иметь всегда доступ

2021-03-30 07:49 UTC, Roman-Kirnos commented on src/server/router/api_v1/places.js
> +router.post('/', { validate: validator.create }, access(), places.create);
У модератора по дефолту доступ

2021-03-30 13:03 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +}
> Мне так нравится писать `middleware`

function handler3() {
  ... (а тут вже реальний код)
}

function handler2() {
  return handler3;
}

function handler() {
  return handler2;
}

function errorHandler() {
  return handler;
}

А який толк від такого написання?

2021-03-30 13:12 UTC, Roman-Kirnos commented on src/server/middleware/errorHandler.js
> +}
Есть только одна промежуточная функция

2021-03-30 13:21 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +}
> Есть только одна промежуточная функция

А яка різниця скільки зайвих функцій 1 чи цілих 10? Суть то одна - це зайве!

2021-03-30 13:32 UTC, Roman-Kirnos commented on src/server/middleware/errorHandler.js
> +}
Мне так нравится middleware писать

2021-03-30 13:32 UTC, Roman-Kirnos commented on src/server/middleware/errorHandler.js
> +}
Если в дальнейшем, нужно будет передать параметр, то она пригодится

2021-03-30 19:43 UTC, DmytroTy commented on src/server/middleware/errorHandler.js
> +}
Якщо так і не можеш придумати що туди передавати, то значить воно не потрібно. Якщо колись стане потрібно тоді й можна буде зробити.

2021-03-31 08:20 UTC, merged