007.2: getExplore function was added
DmytroTy/activity.ck.ua-backend pull request #31
Opened 2021-04-19 08:35 UTC by DmytroTy

2021-04-19 09:44 UTC, Roman-Kirnos commented
Не работает. Я добавил этот метод в ветку 003-users. GET http://localhost:3000/api/v1/users/myself/explore

2021-04-19 11:31 UTC, DmytroTy commented
> Не работает. Я добавил этот метод в ветку 003-users. GET http://localhost:3000/api/v1/users/myself/explore

В мене все працює. В чому в тебе проблема?

2021-04-20 09:37 UTC, DmytroTy commented
Знайшов в чому проблема була й виправив, зараз вже має як слід працювати.

2021-04-20 15:49 UTC, Roman-Kirnos requested changes

2021-04-20 15:49 UTC, Roman-Kirnos commented on src/db/pg/activities.js
> +              WHERE v.user_id = $1 AND deleted_at IS NULL)
Не правильно работает, если установлено `category_id`
![Screenshot from 2021-04-20 18-48-57](https://user-images.githubusercontent.com/56438694/115426363-1a06f100-a209-11eb-8991-cb65a6f21533.png)

2021-04-20 16:01 UTC, Roman-Kirnos commented
Еще есть ошибка, если категория не существует
![Screenshot from 2021-04-20 19-00-46](https://user-images.githubusercontent.com/56438694/115428157-c8f7fc80-a20a-11eb-84da-bb52d40d0ba3.png)

2021-04-20 16:42 UTC, DmytroTy commented on src/db/pg/activities.js
> +              WHERE v.user_id = $1 AND deleted_at IS NULL)
Так, виправив (в мене було замало місць, що не помітив різниці).

2021-04-20 16:48 UTC, DmytroTy commented
> Еще есть ошибка, если категория не существует
> Стоит ли обрабатывать?

Так не шукай космічних проблем. Категорії мають приходити тільки ті що є в БД, вручну їх змінювати ні в кого можливості немає. А робити ще запит для перевірки чи є категорія так про всяк випадок аби тільки було, мабуть немає ніякого сенсу, бо у відповідь однак помилку має відправити.

2021-04-20 18:29 UTC, Roman-Kirnos commented
Я не про запрос на проверку, а сделать так, что бы обрабатывало ошибку

2021-04-21 06:32 UTC, Roman-Kirnos commented on src/db/pg/activities.js
> +        return res.rows[0];
Что если сделать, что бы возвращало -1, если не найдено и тогда обработать это исключение?

``` sql
SELECT COUNT(*)
              FROM places
              WHERE ${categoryId ? 'category_id = $2 AND' : ''} moderated AND deleted_at IS NULL || -1 // ИЛИ -1
```

2021-04-21 07:56 UTC, DmytroTy commented on src/db/pg/activities.js
> +        return res.rows[0];
Це не JS тобі з його "фішками", в SQL таке мабуть не пройде.

2021-04-21 07:57 UTC, DmytroTy commented
> Я не про запрос на проверку, а сделать так, что бы обрабатывало ошибку

ОК, обробка помилки не проблема, додав, тепер це буде вже помилка користувача на виході.

2021-04-21 08:37 UTC, merged