003 users: reviews, explore
DmytroTy/activity.ck.ua-backend pull request #32
Opened 2021-04-19 09:47 UTC by Roman-Kirnos

Explore not working. Need to check it

2021-04-20 08:52 UTC, DmytroTy requested changes
Не забудь що спочатку ще потрібно закінчити з функціями роботи з БД, і там я вчора змінив одну (тут поки немає відповідних змін її назви).

2021-04-20 08:52 UTC, DmytroTy commented on src/config/index.js
> +  },
Це використовуєш тільки в одному файлі,
це зовсім не залежить від бекенду,
й це не буде змінюватись в майбутньому,
тому немає ніяких причин для його розміщення в конфігі!

2021-04-20 08:52 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  createReview,
Бачив, що вчора я цю функцію переробив на більш потрібний нам варіант?

2021-04-20 08:52 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  ctx.body = { reviews };
Знову як завжди: вкладати в ще один об'єкт для дублювання назв не потрібно!

2021-04-20 08:52 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  await deleteReviewDB({ ...ctx.request.body, id: reviewId });
Тут потрібно передавати не об'єкт, а лише тільки id !

2021-04-20 08:52 UTC, DmytroTy commented on src/server/schema/api_v1/places.js
> +  // }).unknown(),
А що тут по валідації плануєш в майбутньому, бо доступ до інформації в нас і без токена має для всіх бути.

2021-04-20 09:02 UTC, Roman-Kirnos commented on src/config/index.js
> +  },
Константы выносятся в конфиг

2021-04-20 09:17 UTC, Roman-Kirnos commented on src/config/index.js
> +  },
Это спорное решение. Кто знает может быть отзыв будет в дальнейшем 10 звезд. И в конфиге сразу видно какой рейтинг может быть у отзыва

2021-04-20 09:45 UTC, DmytroTy commented on src/config/index.js
> +  },
> Константы выносятся в конфиг

Не абсолютно всі на проекті прямо в конфіг, деякі є локальні, наприклад те що тільки для валідації даних що отримуєш не є конфігом, бо не впливаєш на те що отримуєш.

2021-04-20 09:46 UTC, DmytroTy commented on src/config/index.js
> +  },
> Кто знает может быть отзыв будет в дальнейшем 10 звезд.

А де ти бачив рейтинг з 10 зірок?
От і уточни на загальному обговоренні наскільки можлива така зміна.

2021-04-20 09:54 UTC, DmytroTy commented
Більше питань немає.

2021-04-20 10:18 UTC, Roman-Kirnos commented on src/config/index.js
> +  },
Рейтинг от 1 до 5 - бизнес логика. В коде такое потерять не лучшее решение. А в конфиге всегда есть доступ к этим значениям

2021-04-20 10:24 UTC, DmytroTy commented on src/config/index.js
> +  },
Зачекай, ти ж тільки перевіряєш що прийшло з фронтенда, а вся ця бізнес логіка виключно на фронтенді, й бекенд до неї відношення не має.

2021-04-21 06:45 UTC, Roman-Kirnos commented on src/config/index.js
> +  },
Это не только к фронтенду относится. Потому, что наш сервер тоже учавствует в работе, мы не просто храним данные, мы должны их и проверять. Потому, что фронтенд у нас один, но кто-то например с постмена подключится и фронтенд уже изменится и тогда у нашего фронтенда будут не правильные данные потому, что мы не провалидировали.

И ты сам говорил, что согласен за проверку.

Нормально, что конфиг будет расти. Менторы говорили, что лучше все выносить в конфиг. И это потому, что бы видны были все константы в одном месте. И в будущем не нужно будет просматривать файлы проверок, что бы найти в них константу.
И мы точно не знаем, будет ли рейтинг меняться в будущем. Сегодня думаю одно, а завтра уже могу совсем другое.

2021-04-21 16:08 UTC, DmytroTy approved these changes
І змердж вже актуальну версію develop, щоб зайвого не було в цьому пулл реквесті.

2021-04-21 16:08 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +  '/:id/reviews/:userId',
Дивлюсь id стандартно тут зрозуміло, а от userId таки не зрозуміло.
Може краще все ж в самому body його передавати?

2021-04-21 16:08 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  page = parseInt(page, 10);
І ще згадав (це вже таке - не важливе) в тебе ж була спеціально функція для цього: paginationAndAccessibility

2021-04-21 16:16 UTC, DmytroTy commented on src/server/schema/api_v1/places.js
> +    rating: Joi.number().integer().min(RATING.MIN).max(RATING.MAX).required(),
І ще пропустив при оновленні .required() до rating тут зайвий!

2021-04-21 17:47 UTC, Roman-Kirnos commented on src/server/router/api_v1/places.js
> +  '/:id/reviews/:userId',
А что если в `query` передавать?

2021-04-21 18:18 UTC, DmytroTy commented on src/server/router/api_v1/places.js
> +  '/:id/reviews/:userId',
А який сенс частину body відривати й передавати в query де однак не зрозуміло що воно й чого там робить.

2021-04-22 05:34 UTC, DmytroTy commented on src/server/controller/api_v1/places.js
> +  await updateReviewDB({ ...ctx.request.body, place_id: placeId, user_id: userId });
Ще тут рядок 126 взагалі зайвий, далі весь об'єкт body передаєш, тому немає потреби з нього виокремлювати user_id !

2021-04-22 08:53 UTC, DmytroTy approved these changes

2021-04-22 08:57 UTC, DmytroTy commented on src/server/controller/api_v1/utils.js
> +  const { id: userId, role: userRole } = user;
.authPayload тут забув! Через те й не працює вже.

2021-04-22 09:58 UTC, merged