011 search
DmytroTy/activity.ck.ua-backend pull request #39
Opened 2021-04-23 16:39 UTC by DmytroTy

2021-04-23 20:02 UTC, Roman-Kirnos requested changes

2021-04-23 20:02 UTC, Roma-Kyrnis commented on src/db/pg/events.js
> +    searchEvents: async (searchString, limit, page) => {
Предлагаю изменить название параметра на `name` или другое подходящее (`searchName`, `byName`). Так понятней

2021-04-23 20:02 UTC, Roman-Kirnos commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
`category_id` это опциональное поле потому, что поиск с главной страницы без категории.

Еще нужно `type_id` добавить

2021-04-23 20:17 UTC, Roman-Kirnos commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
И поиск по accessibility и dog_friendly, child_friendly тоже может быть

2021-04-24 07:09 UTC, DmytroTy commented on src/db/pg/events.js
> +    searchEvents: async (searchString, limit, page) => {
А для чого змінювати на незрозуміле?
Як рядок пошуку назвати краще ніж "рядок пошуку"?

2021-04-24 07:10 UTC, DmytroTy commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
> `category_id` это опциональное поле потому, что поиск с главной страницы без категории.

Так і є, працюватиме й без нього, але в основному буде майже завжди використовуватись.

2021-04-24 07:11 UTC, DmytroTy commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
> Еще нужно `type_id` добавить

Пошук тільки по назві місця, яким боком ще щось нав'язувати?

2021-04-24 07:16 UTC, DmytroTy commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
> И поиск по accessibility и dog_friendly, child_friendly тоже может быть

Фільтри для зацікавлених є само собою майже на кожній сторінці, й побачити їх не проблема. А пошук за назвою це вже зовсім інший функціонал!

2021-04-25 12:59 UTC, Roman-Kirnos commented on src/db/pg/events.js
> +    searchEvents: async (searchString, limit, page) => {
Что бы было понятно по какому параметру ищет

2021-04-25 13:03 UTC, Roman-Kirnos commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
> > `category_id` это опциональное поле потому, что поиск с главной страницы без категории.
> 
> Так і є, працюватиме й без нього, але в основному буде майже завжди використовуватись.

Я к тому, что передавать пустой параметр каждый раз не лучшее решение, лучше его вынести в конец как дополнительное поле

2021-04-27 06:54 UTC, Roman-Kirnos commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
category_id это опциональное поле. Предлагаю сделать его последним параметром передаваемым в функцию

2021-04-27 07:23 UTC, DmytroTy commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
categoryId основний з параметрів на кожній сторінці категорій, а пошук без нього (на головній) дуже опціональний і поки остаточно не вирішили чи він там взагалі потрібен щоб не перевантажувати головну й не додавати зайвих сторінок.

2021-04-27 10:40 UTC, DmytroTy commented on src/db/pg/places.js
> +    searchPlaces: async (categoryId, searchString, limit, page) => {
От обговорили й прийшли до ще кращого рішення - пошук тільки глобальний зовсім без цього параметру, так і переробив.

2021-04-27 10:42 UTC, DmytroTy commented on src/db/pg/events.js
> +    searchEvents: async (searchString, limit, page) => {
Так як варіант пошуку тільки один єдиний, то не вважаю за потрібне розписувати його параметри в назві функції, а сам параметр названий належним чином.

2021-04-28 10:04 UTC, merged