002.1 organizations server CRUD
DmytroTy/activity.ck.ua-backend pull request #4
Opened 2021-03-28 18:52 UTC by Roman-Kirnos

2021-04-02 15:24 UTC, DmytroTy commented
Змердж спочатку актуальну версію з develop щоб не було конфліктів.

2021-04-02 16:22 UTC, DmytroTy requested changes
Для того щоб не доводилось переробляти перш ніж робити спочатку потрібно обговорювати що збираєшся зробити.

2021-04-02 16:22 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
Не зрозуміло для чого функція, коли вже є створення організацій.

2021-04-02 16:22 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
1. 409
2. Тут можливі 2 різні помилки і їх причина описана в повідомленні. Написана тобою не можлива в принципі й жодному з можливих варіантів не відповідає. Навіть доданий 3-й варіант помилки зовсім інший.
3. Замість того щоб змінювати краще віддати готове оброблене повідомлення помилки користувачу!

2021-04-02 16:22 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
Навіщо дана функція взагалі? В нас не було такої потреби навіть в далекому плануванні.

2021-04-02 16:22 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
1. 409
2. Тут можливі 2 різні помилки і їх причина описана в повідомленні. Написана тобою не можлива в принципі й жодному з можливих варіантів не відповідає. Неможливий в принципі, але доданий 3-й варіант помилки описує дану ситуацію, якщо навіть таке відбудеться.
3. Замість того щоб змінювати краще віддати готове оброблене повідомлення помилки користувачу!

2021-04-02 16:22 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +router.post('/', { validate: validator.create }, access(), organizations.create);
Що за єрунда?

2021-04-02 16:22 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +router.get('/approved', { validate: validator.getApproved }, organizations.getApproved);
Не потрібний в принципі.

2021-04-02 16:22 UTC, DmytroTy commented on src/server/schema/api_v1/organizations.js
> +const getApproved = {};
Не потрібно в принципі.

2021-04-03 05:11 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +}
Нет запроса только для создания организации

2021-04-03 05:14 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
База данных не обрабатывает ошибку, что такого пользователя не существует

2021-04-03 05:14 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
Так я й написав, що в нас немає й не заплановано такого окремого запиту, тобто не потрібно його.

2021-04-03 05:17 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +}
Возможна страница получения всех организаций. Я помню Антон говорил раньше

2021-04-03 05:19 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
Отлично текст копируешь

2021-04-03 05:20 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
Если такой огранизации не существует, тогда уведомить пользователя, что не возможно обновить

2021-04-03 05:24 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
> База данных не обрабатывает ошибку, что такого пользователя не существует

А я тобі про що пишу? Ти отримуєш зовсім інші помилки від БД а користувачу відповідаєш, що користувача немає. Потрібно правильно відповідати що сталось, а не видумувати стандартні відповіді одним на всі варіанти.

2021-04-03 05:27 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
> Возможна страница получения всех организаций. Я помню Антон говорил раньше.
> Возможно модератору пригодится такая информация

Зараз є отримання повністю всіх організацій за що говорив Антон. А таких не всіх та ще й на сторінку яку не збирались робити (для чого вона взагалі?) на пам'ятаю.

2021-04-03 05:29 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
> Отлично текст копируешь

А що я зроблю як ти код копіюєш вже 3-й раз з однією й тією помилкою (в попередньому Пулл реквесті я це вже писав)?

2021-04-03 05:30 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
> Если такой огранизации не существует, тогда уведомить пользователя, что не возможно обновить

А я тобі про що пишу? Ти отримуєш зовсім інші помилки від БД а користувачу відповідаєш, що організації немає (чого в принципі навіть не може бути). Потрібно правильно відповідати що сталось, а не видумувати стандартні відповіді одним на всі варіанти.

2021-04-03 05:52 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
Так предложи решение

2021-04-03 05:56 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
throw ctx.throw(409, err.message);

2021-04-03 06:01 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
Это не логично. Может упасть ошибка, которую пользователю нельзя показывать

2021-04-03 06:02 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +}
Модератор может создавать организации

2021-04-03 06:11 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
> Это не логично. Может упасть ошибка, которую пользователю нельзя показывать

Точно, в тебе ж тут вище:     if (err.name === 'DatabaseError') throw err;  вже оброблені помилки.
А далі, якщо впаде будь - яка 500, то ти користувачу відповіси, що такого користувача немає? Логічно цей рядок єресі просто взагалі прибрати!

2021-04-03 06:15 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
Логичней было бы, если база данных такую ошибку обработала

2021-04-03 06:22 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
І тут виходить аналогічно цей рядок взагалі потрібно прибрати, бо якщо впаде помилка при оновленні, то вона впаде ще раніше!

2021-04-03 06:25 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
Ми ж обговорили, що нікому взагалі не потрібні такі пусті організації модератора без жодного місця!

2021-04-03 06:33 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
> Логичней было бы, если база данных такую ошибку обработала

І як це логічно щоб користувач, який зайшов на сторінку з перевіреним токеном не існував в БД?

2021-04-03 06:41 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
Если организации с `id` не существует, тогда ошибки от базы не будет. Но это нужно обработать.

Например, если без этой строки обновляют организацию. Если её не существует, то им вернется, что она успешно обновлена, но на самом деле ничего не изменилось

2021-04-03 06:52 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
> Если организации с `id` не существует, тогда ошибки от базы не будет. Но это нужно обработать.
> 
> Например, если без этой строки обновляют организацию.

В тебе є перевірка `id` і в мене також є і викидає помилку! Дві перевірки не можна обійти вже ніяк!


> Если её не существует, то им вернется, что она успешно обновлена, но на самом деле ничего не изменилось

Зрозумів який випадок може бути, тоді потрібно.

2021-04-03 07:39 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
І взагалі потрібно це значно краще обробляти: кожен запит на оновлення спочатку перевірити щоб користувач редагував тільки власні дані, а інакше взагалі віддавати помилку 403 і не пропускати такі запити до БД!

2021-04-03 07:51 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
> > Если организации с `id` не существует, тогда ошибки от базы не будет. Но это нужно обработать.
> > Например, если без этой строки обновляют организацию.
> 
> В тебе є перевірка `id` і в мене також є і викидає помилку! Дві перевірки не можна обійти вже ніяк!
> 
> > Если её не существует, то им вернется, что она успешно обновлена, но на самом деле ничего не изменилось
> 
> Зрозумів який випадок теоретично може бути при взломі веб-додатка, тоді потрібно і вже 404 має бути.

У тебя проверка пустая ли `id`, но не существует ли организация с такой `id`

А то что ты делаешь двойную проверку. Скажи зачем?

2021-04-03 08:09 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +}
Если это нужно будет модератору в будущем, то оно уже реализовано и протестировано на сервере

2021-04-03 08:11 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
> Ми ж обговорили, що нікому взагалі не потрібні такі пусті організації модератора без жодного місця!

2021-04-03 08:16 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +}
> Ми ж обговорили, що нікому взагалі не потрібні такі пусті організації модератора без жодного місця!

Або ж такі пропозиції винось на загальне обговорення й там тобі всі скажуть те ж саме.

2021-04-03 08:54 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
> А то что ты делаешь двойную проверку. Скажи зачем?

Я вже відповідав тобі, що перевіряю по мінімуму тільки необхідні параметри щоб не впав запит до БД (особливо специфічні обмеження). Але в тебе незважаючи на сотні перевірок ще не все перевіряється, тому однак потрібно доробити повністю, або мені ще більше перевірок дописати.

2021-04-03 13:37 UTC, Roman-Kirnos commented
Еще есть какие-то замечания по коду?

2021-04-03 14:46 UTC, DmytroTy commented
> Еще есть какие-то замечания по коду?

Попередні 2 залишились.

І також там же написав пропозицію: зробити перевірку й надавати можливість користувачам оновлювати тільки свої власні організації.

2021-04-04 07:28 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +router.get('/proposed', { validate: validator.getProposed }, organizations.getProposed);
Здається і в цьому роуті навряд чи виникне потреба. Тому поки як мінімум доведеться закоментувати даний рядок.

2021-04-05 06:07 UTC, Roman-Kirnos commented
> Попередні 2 залишились.
Я думаю пускай будет функция создания. Если она в будущем пригодится, я думаю так. То такой метод уже реализован. Это стандартная функция из CRUD, которая должна быть по стандарту. А не разработчики не захотели делать или подумали, что им не пригодится и не добавляли.

> І також там же написав пропозицію: зробити перевірку й надавати можливість користувачам оновлювати тільки свої власні організації.
У нас такого по функционалу нет. Обновлять все организации может только модератор. И пользователь не знает id созданной организации, особенно той которая не прошла проверку.

2021-04-05 06:07 UTC, Roman-Kirnos commented on src/server/router/api_v1/organizations.js
> +router.get('/proposed', { validate: validator.getProposed }, organizations.getProposed);
Этот роутер нужен для модерации

2021-04-05 07:27 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +router.get('/proposed', { validate: validator.getProposed }, organizations.getProposed);
Для модерації буде необхідним зовсім інший роут, а цей взагалі сумніваюсь щоб пригодився, тому й написав закоментувати.

2021-04-05 07:32 UTC, DmytroTy commented
> Я думаю пускай будет функция создания. Если она в будущем пригодится, я думаю так. То такой метод уже реализован. Это стандартная функция из CRUD, которая должна быть по стандарту. А не разработчики не захотели делать или подумали, что им не пригодится и не добавляли.

Ми не раз обговорювали той момент, що нам не потрібно створювати пусті організації зовсім без місць, тому й немає в цьому роуті жодної потреби - він абсолютно зайвий.



> У нас такого по функционалу нет. Обновлять все организации может только модератор. И пользователь не знает id созданной организации, особенно той которая не прошла проверку.

Добре зараз такого немає в запланованому. Тоді в цьому разі видали той рядок зовсім, бо модератор може редагувати тільки існуючі організації, id яких він попередньо отримав, й інших варіантів в нас відповідно не заплановано, тому там помилок таких не може бути в принципі!

2021-04-05 07:57 UTC, Roman-Kirnos commented
Я думаю стоит оставить создание и проверку на правильность id.
Есть еще исправления по коду?

2021-04-05 08:20 UTC, DmytroTy commented
> Я думаю стоит оставить создание и проверку на правильность id.
> Есть еще исправления по коду?

Як я тобі вже відповідав повторюю: всі власні непідтримані ідеї винось на загальне обговорення (тому що це питання вже було обговорено й ніхто його не підтримав)!

2021-04-05 08:37 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
Возможно

2021-04-05 08:38 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
Проверка нужна

2021-04-05 08:38 UTC, Roman-Kirnos commented on src/server/router/api_v1/organizations.js
> +router.get('/proposed', { validate: validator.getProposed }, organizations.getProposed);
Так этот роутер для модерации и есть

2021-04-05 08:48 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
> Возможно

Як мені трактувати одне єдине слово?

2021-04-05 08:52 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
Возможно, что бы не существовал пользователь

2021-04-05 08:54 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
> Проверка нужна

Помилка принципово не можлива!

2021-04-05 08:55 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +router.get('/proposed', { validate: validator.getProposed }, organizations.getProposed);
Сам по собі він абсолютно не потрібен, бо є потреба в іншому, а цей не буде ніколи використаний!

2021-04-05 08:56 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +    throw ctx.throw(400, `User with id ${userId} does not exist`);
> Возможно, что бы не существовал пользователь

І як такий не існуючий в БД користувач пройде авторизацію й перевірку токена щоб сюди потрапити?

2021-04-05 14:25 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
Давай тут як домовились при обговоренні, на такий рідкісний випадок зроби правильний код помилки 404 у відповіді.

2021-04-05 14:28 UTC, DmytroTy commented on src/server/router/api_v1/organizations.js
> +router.get('/proposed', { validate: validator.getProposed }, organizations.getProposed);
Я забув цей момент підняти при обговоренні. Ти ж як зацікавлений у вирішенні конфлікту маєш однак його підняти на обговоренні.

А взагалі тут краще робити метод отримання однієї організації по її id, який має бути потрібним.

2021-04-05 20:08 UTC, Roman-Kirnos commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
Это не 404. Здесь как я пологаю 400 или 409, но точно не 404

2021-04-06 07:15 UTC, merged

2021-04-06 08:43 UTC, DmytroTy commented on src/server/controller/api_v1/organizations.js
> +  ctx.assert(organization, 400, `Organization with id ${id} doesn't exist`);
404 = Параметри запиту правильні, але з такою id організації просто не знайдено.