002.5 search
DmytroTy/activity.ck.ua-backend pull request #44
Opened 2021-04-29 08:11 UTC by Roman-Kirnos

2021-04-29 13:44 UTC, DmytroTy commented
Ми ж домовились на загальному обговоренні, що пошук тільки глобальний і ніяких інших варіантів, й без жодних фільтрів!

2021-04-29 14:38 UTC, Roman-Kirnos commented
Точно. Сейчас подправлю

2021-04-29 15:05 UTC, DmytroTy commented
Нагадав же: ніяких фільтрів, просто пошук.

2021-04-29 16:02 UTC, Roman-Kirnos commented
Покажи в коде

2021-04-29 17:54 UTC, DmytroTy requested changes
> Покажи в коде

Видалив зайві коміти, тоді ладно.

2021-04-29 17:54 UTC, DmytroTy commented on src/server/router/api_v1/search.js
> +router.get('/', { validate: validator.global }, search.global);
То напиши вже відразу перевірку доступності для всіх відвідувачів сайту як скрізь.

2021-04-29 18:33 UTC, Roman-Kirnos commented on src/server/router/api_v1/search.js
> +router.get('/', { validate: validator.global }, search.global);
Зачем?

2021-04-29 18:34 UTC, Roman-Kirnos commented on src/server/router/api_v1/search.js
> +router.get('/', { validate: validator.global }, search.global);
В этом запросе `ID` пользователя не используется

2021-04-30 15:09 UTC, DmytroTy commented on src/server/router/api_v1/search.js
> +router.get('/', { validate: validator.global }, search.global);
Тоді ОК.

2021-04-30 15:10 UTC, merged