010: opened filter was added
DmytroTy/activity.ck.ua-backend pull request #46
Opened 2021-04-29 15:03 UTC by DmytroTy

2021-04-29 17:10 UTC, Roman-Kirnos requested changes

2021-04-29 17:10 UTC, Roma-Kyrnis commented on src/db/pg/places.js
>            values,
Зачем столько query запросов?

Так же не будет повторяться `AND` в конце всех query.
Один сделать, например `const query = []` и потом поместить в `WHERE` с помощью `query.join(' AND ')`;

2021-04-29 17:10 UTC, Roma-Kyrnis commented on src/db/pg/places.js
>            values,
![Screenshot from 2021-04-29 19-22-00](https://user-images.githubusercontent.com/56438694/116585292-eb7fc900-a920-11eb-8e44-5a8f1077e01d.png)
Здесь тоже провести бы рефакторинг, что бы в конце все параметры соединялись `query.join(' AND ')`

2021-04-29 17:10 UTC, Roman-Kirnos commented on src/db/pg/places.js
> +              > (CURRENT_TIME AT TIME ZONE 'Europe/Kiev')::time + INTERVAL '30 minutes'
Интервал убрать

2021-05-05 12:43 UTC, DmytroTy commented on src/db/pg/places.js
>            values,
А в чому проблема, так хоч видно структуру запиту, не повністю кожна частина тут же розписана, але хоч блоки видно. А пропонуєш просто "query" в яком все (не зрозуміло що в самих запитах) буде міститись, виглядатиме простіше, але розібратись в коді що до чого буде тільки складніше.

2021-05-05 12:50 UTC, DmytroTy commented on src/db/pg/places.js
> +              > (CURRENT_TIME AT TIME ZONE 'Europe/Kiev')::time + INTERVAL '30 minutes'
Видалив

2021-05-05 17:13 UTC, Roma-Kyrnis commented
Отлично)

2021-05-05 17:13 UTC, merged