002.3 faker places and default(user with organization)
DmytroTy/activity.ck.ua-backend pull request #5
Opened 2021-03-28 18:55 UTC by Roman-Kirnos

2021-04-02 15:23 UTC, DmytroTy commented
Змердж спочатку актуальну версію з develop щоб не було конфліктів.

2021-04-02 20:58 UTC, DmytroTy requested changes
Срач в config розширюєш?

2021-04-02 20:58 UTC, DmytroTy commented on .env.example
> -MODERATOR_PASSWORD=12345678
Щось таке якраз нам знадобиться для запуску сервера.

2021-04-02 20:58 UTC, DmytroTy commented on README.md
> +sudo docker exec -it node npm run seeds:places count=10 user_id=1 organization_id=1
В більшості це не буде працювати й мало хто здогадається (й зможе подивитись) справжні id в БД.

2021-04-02 20:58 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
Це взагалі не потрібно.

2021-04-02 20:58 UTC, DmytroTy commented on src/config/index.js
>    },
Це взагалі тимчасово на початковому етапі розробки. Та й тут йому взагалі не місце. Прямо в faker все це й прописуй.

2021-04-02 20:58 UTC, DmytroTy commented on src/config/index.js
> +    ORGANIZATION_ID: 1,
На практиці таких id скоріше за все не буде й буде помилка виконання.

2021-04-02 20:58 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Що за єрунда, можна було й самий звичайний цикл for зробити, а не фігню городити.

2021-04-02 20:58 UTC, DmytroTy commented on src/db/seeds/index.js
> +      log.info(place, `Places created`);
Оце вже жирний буде лог - по 2 рази кожне створене місце повиводити!
"Places" - граматична помилка, це ж до кожного місця дописується.

2021-04-02 20:58 UTC, DmytroTy commented on src/db/seeds/index.js
> +        organization_id: organizationId,
Переданих значень в БД скоріше за все не знайдеться й впаде помилка.

2021-04-02 20:58 UTC, DmytroTy commented on src/lib/api_v1/faker.js
> +    const endMinutes = faker.random.number({ min: 0, max: 24 });
Мабуть 60 хотів, а не 24?

2021-04-02 20:58 UTC, DmytroTy commented on package.json
> +    "faker": "^5.5.2",
Не в той розділ поставив, на продакшені воно не потрібно!

2021-04-03 05:21 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
Додай у перевірку обов'язковість параметрів: category_id, _page, _limit бо без них не можливо однозначно трактувати запит і з фронтенда вони завжди приходять.

А це дефолтне - не потрібно загадувати чого б хотілось фронтенду, що саме потрібно прийде в запиті.

2021-04-03 05:29 UTC, Roman-Kirnos commented on src/config/index.js
>        PAGE: 1,
Если `_page, _limit` не будет, не логично ошибку выбрасывать из-за этого

2021-04-03 05:34 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
Ще раз повторюю параматри: category_id, _page, _limit фронтенд предає обов'язково! Інакше просто було б не можливо зрозуміти що саме вони хочуть отримати й така ситуація можлива виключно при пошкодженні запиту при передачі по мережі, а це вже однозначно - помилка мережі!

2021-04-03 05:37 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
Ще раз повторюю параматри: category_id, _page, _limit фронтенд предає обов'язково! Інакше просто було б не можливо зрозуміти що саме вони хочуть отримати й така ситуація можлива виключно при пошкодженні запиту при передачі по мережі, а це вже однозначно - помилка мережі! І навіть в такому рідкісному випадку однозначно не варто присилати у відповіді не те що просили!

2021-04-03 06:26 UTC, Roman-Kirnos commented on src/config/index.js
>        PAGE: 1,
![Screenshot from 2021-04-03 09-23-54](https://user-images.githubusercontent.com/56438694/113470466-930ef600-945e-11eb-997b-a6a1aa93fcf4.png)
`category_id` не может быть обязательной

2021-04-03 06:36 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
Вибачаюсь, це ми справді з фронтендом так домовились.
А також домовились, що _page, _limit є обов'язковими як і наявність ще одного з параметрів категорія або тип, що цілком логічно.

2021-04-03 06:43 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Звичайний for буде ще краще, і лінтер тоді не буде сваритись на зайве!

2021-04-03 08:00 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Обычный `for` работает только с синхронным кодом

2021-04-03 08:07 UTC, Roman-Kirnos commented on .env.example
> -MODERATOR_PASSWORD=12345678
Это не относится к faker

2021-04-03 08:09 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Ні тільки forEach має обмеження в тому, що працює тільки з синхронним кодом.
А звичайний for, на відміну від нього, добре працює з асинхронним кодом. В цьому місці його застосування найбільш очікуване, бо в тебе є тільки кількість ітерацій, які необхідно виконати й більш нічого.

2021-04-03 08:11 UTC, DmytroTy commented on .env.example
> -MODERATOR_PASSWORD=12345678
Так це й файл .env

2021-04-03 13:51 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
![Screenshot from 2021-04-03 16-50-01](https://user-images.githubusercontent.com/56438694/113480390-ab056a80-949c-11eb-80eb-8c9f40043b6c.png)
Я проверил, работает `await` в обычном `for`. Но тогда eslist ругается, что нельзя `await inside a loop`

2021-04-03 14:49 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
> ![Screenshot from 2021-04-03 16-50-01](https://user-images.githubusercontent.com/56438694/113480390-ab056a80-949c-11eb-80eb-8c9f40043b6c.png)
> Я проверил, работает `await` в обычном `for`. Но тогда eslist ругается, что нельзя `await inside a loop`

Так тобі однаково потрібно await в циклі використати, зате не свариться на помилки написання коду.

2021-04-05 06:08 UTC, Roman-Kirnos commented
Закроешь pull request?

2021-04-05 07:23 UTC, DmytroTy commented
> Закроешь pull request?

Так ти виправив тільки одну помилку й одне зауваження!
А як на рахунок інших? Чи думаєш помилки можна просто проігнорувати?

2021-04-05 08:08 UTC, Roman-Kirnos commented
Исправил документацию. По остальным исправление не нужно или уже есть.
Есть еще правки по коду?

2021-04-05 08:24 UTC, DmytroTy commented
> Исправил документацию.

Це ще не все.


> По остальным исправление не нужно или уже есть.

Потрібно й досі не виправлено навіть помилки, інакше б я про це не писав.

2021-04-05 08:34 UTC, Roman-Kirnos commented on package.json
> +    "faker": "^5.5.2",
Я обновил версию. Это не ошибка

2021-04-05 08:34 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +        organization_id: organizationId,
Это не ошибка

2021-04-05 08:34 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Это уже исправлено

2021-04-05 08:34 UTC, Roman-Kirnos commented on src/config/index.js
> +    ORGANIZATION_ID: 1,
Это уже убрано из конфига

2021-04-05 08:35 UTC, Roman-Kirnos commented on src/config/index.js
>    },
Это вынесено

2021-04-05 08:35 UTC, Roman-Kirnos commented on src/config/index.js
>        PAGE: 1,
Категория и тип уже проверяются

2021-04-05 08:35 UTC, Roman-Kirnos commented on README.md
> +sudo docker exec -it node npm run seeds:places count=10 user_id=1 organization_id=1
Документация обновлена

2021-04-05 08:36 UTC, Roman-Kirnos commented on .env.example
> -MODERATOR_PASSWORD=12345678
Это не нужный код. Который использовался, только в faker

2021-04-05 08:57 UTC, DmytroTy commented on package.json
> +    "faker": "^5.5.2",
> Не в той розділ поставив, на продакшені воно не потрібно!

Це потрібно ставити в розділ девелопмент!!!

2021-04-05 08:58 UTC, DmytroTy commented on src/db/seeds/index.js
> +        organization_id: organizationId,
Від незнайдених даних впаде помилка. Можна ж зробити нормально щоб таких ситуацій не виникало!

2021-04-05 14:42 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
![Зняток екрану як 2021-04-05 17-39-04](https://user-images.githubusercontent.com/44680326/113586449-32d2ac80-9636-11eb-8147-e6a944c107a7.png)
Це так і залишилось.

2021-04-05 14:44 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
![Зняток екрану як 2021-04-05 17-43-34](https://user-images.githubusercontent.com/44680326/113586721-8218dd00-9636-11eb-8ad3-bcc75d58d0dc.png)
Тут так і залишилось створення зовсім не потрібного масиву!

2021-04-05 20:13 UTC, Roman-Kirnos commented on src/config/index.js
>        PAGE: 1,
Я думаю не логично, что бы запрос не работал, без указания страницы и количество мест на ней

2021-04-05 20:13 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Потому, что я использую `for await`

2021-04-05 20:14 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
> ![Screenshot from 2021-04-03 16-50-01](https://user-images.githubusercontent.com/56438694/113480390-ab056a80-949c-11eb-80eb-8c9f40043b6c.png)
> Я проверил, работает `await` в обычном `for`. Но тогда eslist ругается, что нельзя `await inside a loop`

Eslint предупреждает, что лучше в обычном `for` не использовать await

2021-04-05 20:15 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +      log.info(place, `Places created`);
Я изменил лог

2021-04-05 20:16 UTC, Roman-Kirnos commented on src/db/seeds/index.js
> +        organization_id: organizationId,
Так предложи это нормально, а не говори о чом-то заумном

2021-04-05 20:16 UTC, Roman-Kirnos commented on package.json
> +    "faker": "^5.5.2",
Это ветка `faker`. Значит здесь и нужно обновлять его

2021-04-06 07:15 UTC, merged

2021-04-06 08:47 UTC, DmytroTy commented on src/config/index.js
>        PAGE: 1,
А на фронтенді вирішили, що передавати їх обов'язково потрібно і я їх рішення підтримую!

2021-04-06 08:48 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Запитай у менторів як правильно зробити цикл коли відома тільки кількість ітерацій.

2021-04-06 08:50 UTC, DmytroTy commented on src/db/seeds/index.js
> +        organization_id: organizationId,
Добре я зроблю виправлення помилок і відправлю Пулл реквестом.

2021-04-06 08:52 UTC, DmytroTy commented on package.json
> +    "faker": "^5.5.2",
> Это ветка `faker`. Значит здесь и нужно обновлять его

Я нічого проти оновлення й не мав.
А от так як на продакшені фейкер не використовується, то його ставлять в devDependency!

2021-04-06 08:53 UTC, DmytroTy commented on src/db/seeds/index.js
> +      log.info(place, `Places created`);
Змін не приходило!

2021-04-06 09:16 UTC, DmytroTy commented on src/db/seeds/index.js
> +  for await (const {} of new Array(count)) {
Так як ітератор тут не використовуєш, то й немає ніякої потреби в for await (хоча звісно помилку він і не викидає, але явно не для таких випадків зроблений).

2021-04-07 08:38 UTC, Roman-Kirnos commented on package.json
> +    "faker": "^5.5.2",
У меня не получилось использовать devDependency в коде

2021-04-07 10:32 UTC, DmytroTy commented on package.json
> +    "faker": "^5.5.2",
> У меня не получилось использовать devDependency в коде

Це вже зовсім не серйозна відмазка.
Ти ж казав в development енвайронменті запускаєш і тільки фронтенду з якого сь дива нав'язав в production запускати!